modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="chewy_cheeses"
version="1.0.1"
displayName="Chewy Cheeses"

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
credits="Burning Sulphur & Fate of Adrastus" #optional

# The authors of the mod, displayed in the mod UI (optional)
#authors=""

# The description text for the mod (multi line!) (#mandatory)
description='''
An addon mod for Brewin' and Chewin' that adds compatibility with cheeses from other mods,
and adds cheeses with items from other mods.
'''

[[mixins]]
config = "chewy_cheeses.mixins.json"
[[mixins]]
config = "chewy_cheeses.dungeonsdelight.mixins.json"
requiredMods=["dungeonsdelight"]

[[dependencies.chewy_cheeses]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.224,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chewy_cheeses]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."chewy_cheeses"]]
    modId= "brewinandchewin"
    type = "required"
    versionRange="[4.4.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."chewy_cheeses"]]
    modId= "farmerspizzeria"
    type = "optional"
    ordering="AFTER"
    side="BOTH"

[[dependencies."chewy_cheeses"]]
    modId= "netherexp"
    type = "optional"
    versionRange="[2.4.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."chewy_cheeses"]]
modId= "sniffer"
type = "optional"
ordering="AFTER"
side="BOTH"

[[dependencies."chewy_cheeses"]]
modId= "hearthandharvest"
type = "optional"
ordering="AFTER"
side="BOTH"

[[dependencies."chewy_cheeses"]]
    modId= "dungeonsdelight"
    type = "optional"
    versionRange="[1.4.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."chewy_cheeses"]]
    modId= "endersdelight"
    type = "optional"
    versionRange="[1.2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."chewy_cheeses"]]
    modId= "environmental"
    type = "optional"
    versionRange="[5.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."chewy_cheeses"]]
    modId= "quark"
    type = "optional"
    versionRange="[4.1-474,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."chewy_cheeses"]]
    modId= "darkerdepths"
    type = "optional"
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."chewy_cheeses"]]
modId= "sniffer"
type = "optional"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"