modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="chewy_cheeses"
version="0.4.0"
displayName="Chewy Cheeses"

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
credits="Burning Sulphur & Fate of Adrastus" #optional

# The authors of the mod, displayed in the mod UI (optional)
#authors=""

# The description text for the mod (multi line!) (#mandatory)
description='''
An addon mod for Brewin' and Chewin' that adds compatibility with cheeses from other mods
'''

[[dependencies.chewy_cheeses]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.219,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chewy_cheeses]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies."chewy_cheeses"]]
    modId= "brewinandchewin"
    type = "required"
    versionRange="[1.20.1-3.2.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."chewy_cheeses"]]
    modId= "rats"
    type = "optional"
    versionRange="[1.20.1-8.1.3,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies."chewy_cheeses"]]
    modId= "netherexp"
    type = "optional"
    versionRange="[2.3.3,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies."chewy_cheeses"]]
    modId= "dungeonsdelight"
    type = "optional"
    versionRange="[1.1.3,)"
    ordering="AFTER"
    side="BOTH"